# Generated by Django 3.2.6 on 2021-08-30 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siteusers', '0001_initial'),
        ('sitestats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitestat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_site_stats', to='siteusers.player'),
        ),
    ]
